### ISSUE TITLE
Deploy plugin as a snap instead of using pip3 for compatibility with certbot

### ISSUE THREAD

**Issue by timk** [runfalk/certbot-dns-glesys#7]
certbot project now recommends and maintain snap instead of PyPi/pip store when installing. This is a request to do the same with this helpful plugin :-)

**certbot**
"While we strongly recommend that most users install Certbot through the snap, you can find alternate installation instructions [here](https://certbot.eff.org/docs/install.html)."

**pip**
pip tool as installation method has been deprecated:
https://www.theregister.com/2021/05/25/pypi_search_error/

**snap store with other plugins**
https://snapcraft.io/search?q=certbot-dns

**Comment by runfalk** [comment]
I have no interest in snaps myself. If someone wants to package this and submit a PR I'd merge it though, provided it is fully automated through CI.

I skimmed the register article and don't really see how this means pip is deprecated as an installation method?

**Comment by timk** [comment]
You are absolutely right that it was only search and not installation which makes it less accessible. One can still find packages via the web UI and then install by through the pip command.

Closing as not planned 🙂
